# Generated by Django 4.2.1 on 2023-05-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Name', models.CharField(max_length=255)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Level', models.IntegerField()),
                ('Department', models.CharField(max_length=2)),
                ('GPA', models.FloatField()),
                ('Status', models.CharField(max_length=8)),
                ('Email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('Date', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
    ]
