# Generated by Django 4.2.1 on 2023-05-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AlterField(
            model_name='student',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Department',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Status',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
