# Generated by Django 4.2.1 on 2023-05-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_phone_alter_student_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Date',
            new_name='BirthDate',
        ),
    ]
