# Generated by Django 4.2.1 on 2023-05-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_department_alter_student_gpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pageAdmins',
            fields=[
                ('Username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
