# Generated by Django 4.2.1 on 2023-05-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_password_pageadmins_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
